language: cpp

matrix:
  include:
  - os: linux
    dist: xenial
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
          - g++-7
    env:
      - BUILD_TYPE=Release
      - COMPILER_LIBCXX=libstdc++11
      - CONFIGURATION=Release
      
install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90; fi

script:
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} .. 
  - make
  - cd test/test-manager
  - ./TestModuleTest

